#!/usr/bin/env node
// Runs one real browser task through the LLM agent and writes a Markdown report
// (metadata + tool-call transcript + the agent's answer) to OUTPUT. Designed to
// run inside the Docker mock-VM, reaching the host's daemon + Playwright MCP only
// over the tunnel — then the .md artifact is picked up from a mounted volume.
import { writeFileSync } from "fs";
import { selectProvider } from "./llm/index.js";
import { McpBridge } from "./mcp.js";

const DAEMON_URL = process.env.DAEMON_URL ?? "http://localhost:3001/mcp";
const PLAYWRIGHT_URL = process.env.PLAYWRIGHT_URL ?? "http://localhost:3000";
const OUTPUT = process.env.OUTPUT ?? "report.md";
const TASK =
  process.env.TASK ??
  "Go to Google and search for something interesting, then summarize the top results as a Markdown list.";

const SYSTEM_PROMPT =
  "You are a browser automation agent driving a real Chrome browser via tools. " +
  "Always open a new tab for your work. If a cookie or consent dialog appears, accept it before continuing. " +
  "After a page navigates or a dialog is dismissed, take a fresh browser_snapshot before clicking — element references from a previous snapshot may be stale. " +
  "Complete the user's task, then respond with a well-structured Markdown report of what you found. " +
  "Use headings, lists, and links, and include the actual data you gathered.";

interface CallRecord {
  name: string;
  args: string;
  ok: boolean;
  ms: number;
}

async function main() {
  const provider = selectProvider(process.env.LLM_PROVIDER || undefined);
  const model = process.env.MODEL || provider.defaultModel;
  if (!provider.isConfigured()) {
    console.error(provider.missingKeyMessage());
    process.exit(1);
  }

  const bridge = new McpBridge(DAEMON_URL, PLAYWRIGHT_URL);
  await bridge.connectDaemon();
  await bridge.connectPlaywright();
  await bridge.listTools(); // populate the source map
  console.log(`Connected. Provider=${provider.name} Model=${model}`);

  // Record every tool call for the report. Display is handled by the provider.
  const transcript: CallRecord[] = [];
  const callTool = async (name: string, args: Record<string, unknown>): Promise<string> => {
    const started = Date.now();
    const argStr = JSON.stringify(args);
    const summary = argStr.length > 120 ? argStr.slice(0, 117) + "…" : argStr;
    try {
      const out = await bridge.callTool(name, args);
      transcript.push({ name, args: summary, ok: true, ms: Date.now() - started });
      return out;
    } catch (err) {
      transcript.push({ name, args: summary, ok: false, ms: Date.now() - started });
      throw err;
    }
  };

  const session = provider.createSession({
    systemPrompt: SYSTEM_PROMPT,
    model,
    listTools: () => bridge.listTools(),
    callTool,
  });

  console.log(`\nTask: ${TASK}\n--- running ---`);
  const startedAt = Date.now();
  let answer = "";
  let error = "";
  try {
    answer = await session.send(TASK);
  } catch (err) {
    error = String(err);
  }
  const finishedAt = new Date();
  const durationS = ((finishedAt.getTime() - startedAt) / 1000).toFixed(1);

  // ── Build the Markdown report ───────────────────────────────────────────────
  const counts = bridge.toolCounts();
  const lines: string[] = [
    `# Agent Task Report`,
    ``,
    `> Generated by the Remote Browser MCP agent running inside the Docker mock-VM,`,
    `> reaching the host's Chrome only through the tunnel.`,
    ``,
    `| Field | Value |`,
    `|---|---|`,
    `| Timestamp | ${finishedAt.toISOString()} |`,
    `| Provider | ${provider.name} |`,
    `| Model | ${model} |`,
    `| Daemon URL | ${DAEMON_URL} |`,
    `| Playwright URL | ${PLAYWRIGHT_URL} |`,
    `| Tools available | ${counts.daemon} daemon + ${counts.playwright} playwright |`,
    `| Duration | ${durationS}s |`,
    `| Tool calls | ${transcript.length} (${transcript.filter((t) => t.ok).length} ok) |`,
    ``,
    `## Task`,
    ``,
    TASK,
    ``,
    `## Tool-call transcript`,
    ``,
  ];
  if (transcript.length === 0) {
    lines.push("_(no tool calls)_");
  } else {
    transcript.forEach((t, i) => {
      lines.push(`${i + 1}. \`${t.name}\` ${t.ok ? "✓" : "✗"} — \`${t.args}\` _(${t.ms}ms)_`);
    });
  }
  lines.push("", `## Result`, "", error ? `**Error:** ${error}` : answer || "_(no answer returned)_", "");

  const md = lines.join("\n");
  writeFileSync(OUTPUT, md, "utf8");
  console.log(`\n--- wrote ${OUTPUT} (${md.length} bytes) ---`);
  process.exit(error ? 1 : 0);
}

main().catch((err) => {
  console.error("FAILED:", err);
  process.exit(1);
});
